spring:
  kafka:
    bootstrap-servers: xxx.xxx.x.xx:9092,xxx.xxx.x.xx:9093,xxx.xxx.x.xx:9094
    producer:
      retries: 3  # 重试次数
      batch-size: 16384 # 每批消息16kb
      buffer-memory: 33554432 # 发送消息缓冲区32M
      acks: 1   # leader成功写入数据
      # key,value 序列化方法
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      enable-auto-commit: false # 偏移量手动提交
      auto-offset-reset: earliest # 重启后offset配置：如果有offset记录，则从之前的位置开始；如果没有，从最早的消息开始
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 500 # 每次poll最多多少条消息
    listener:
      # MANUAL 当每一批poll的数据被消费者监听器处理之后，手动调用ack.acknowledge()后提交offset
      # MANUAL_IMMEDIATE 手动调用ack.acknowledge()方法后，立即提交offset
      ack-mode: manual_immediate